<a href="https://colab.research.google.com/github/Srihari0804/Desicion-Trees/blob/main/Credit_card_fraud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/dataset.csv")

In [ ]:
#practising PCA,MCA,FAMD
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [ ]:
int_col = df.select_dtypes(include=['int64','float64'])

In [ ]:
#first we scale using StandardScaler
scaler = StandardScaler()
int_col = scaler.fit_transform(int_col)

pca = PCA(n_components=0.95,random_state=42)
princ_comp = pca.fit_transform(int_col)
princ_comp_df = pd.DataFrame(princ_comp,columns=[f"Pricipal Comp {i+1}" for i in range(pca.n_components_)])

sum(pca.explained_variance_ratio_)

np.float64(0.9894461222213818)

In [ ]:
import numpy as np

np.sum(pca.explained_variance_ratio_)

np.float64(0.9894461222213818)

In [ ]:
import prince

str_df = df.select_dtypes(exclude=['int64','float64'])

mca = prince.MCA(n_components=2,random_state=42)
mca_axis = mca.fit_transform(str_df)
mca_axis

In [ ]:
pca = PCA(n_components=2)
scaler = StandardScaler()
int_col = scaler.fit_transform(int_col)

principal_comp = pca.fit_transform(int_col)
pca_df = pd.DataFrame(principal_comp,columns=[f"principal component {i+1}" for i in range(2)])

pca.explained_variance_ratio_

array([0.26327434, 0.18618865])

In [ ]:
import numpy as np

In [ ]:
variance_threshold = 0.95
pca_var = PCA(n_components=variance_threshold)
X_reduced_var = pca_var.fit_transform(int_col)

    # Check how many components were chosen
n_components_chosen = pca_var.n_components_
print(f"To retain {variance_threshold:.0%} of the variance, PCA chose {n_components_chosen} components.")
print(f"The new data shape is: {X_reduced_var.shape}")
print(f"Total variance explained: {np.sum(pca_var.explained_variance_ratio_):.2%}\n")

To retain 95% of the variance, PCA chose 7 components.
The new data shape is: (1296675, 7)
Total variance explained: 98.94%

In [ ]:
#running FAMD
#!pip install prince

In [ ]:
import prince

In [ ]:
n_components = 2
famd = prince.FAMD(
        n_components=n_components,
        n_iter=3,          # Number of iterations for the algorithm
        random_state=42    # for reproducibility
    )

# Fit FAMD to the entire DataFrame
famd = famd.fit(df)

# 3. Get the Reduced Dimensions
# We can now transform our original data into the new component space.
reduced_df = famd.transform(df)
reduced_df.columns = [f'component_{i+1}' for i in range(n_components)]

print(f"\nDataFrame with {n_components} FAMD components:")
print(reduced_df.head())

# 4. Explained Inertia
# In FAMD, "explained inertia" is the equivalent of "explained variance" in PCA.
# It tells us how much of the dataset's total variability is captured by the components.
print("\nExplained Inertia by each component:")
print(famd.explained_inertia)

total_explained_inertia = sum(famd.explained_inertia_)
print(f"\nTotal explained inertia by {n_components} components: {total_explained_inertia:.2%}")
print("\nThis means our 2 new features capture",
          f"{total_explained_inertia:.2%} of the information from all original features.")

In [ ]:
import numpy as np

In [ ]:
explained_variance = pca.explained_variance_ratio_
total_explained_variance = np.sum(explained_variance)
total_explained_variance

np.float64(0.44946298772165383)

In [ ]:
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,...,37.7175,-112.4777,258,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0
1296671,1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,...,39.2667,-77.5101,100,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0
1296672,1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,32.9396,-105.8189,899,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0
1296673,1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,...,43.3526,-102.5411,1126,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0
1296674,1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,...,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0

In [ ]:
df[df.is_fraud == 1].merchant.value_counts()

merchant
fraud_Rau and Sons      49
fraud_Kozey-Boehm       48
fraud_Cormier LLC       48
fraud_Doyle Ltd         47
fraud_Kilback LLC       47
                        ..
fraud_Deckow-Dare        1
fraud_Dietrich-Fadel     1
fraud_Kihn-Fritsch       1
fraud_Turner LLC         1
fraud_Hills-Olson        1
Name: count, Length: 679, dtype: int64

###Creating Date

In [ ]:
df['Date'] = df.apply(lambda x: x['trans_date_trans_time'].split(" ")[0],axis=1)

In [ ]:
#Create year and month
df["Year and Month"] = df.apply(lambda x: x['Date'][0:-3],axis = 1)

In [ ]:
#combine first and last to get name
df['Name'] = df.apply(lambda x: x['first']+" "+x['last'],axis=1)

###Creating location

In [ ]:
#before creating loc lets normalize lat and long
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler2 = StandardScaler()

df.lat = scaler.fit_transform(df[['lat']])
df['long'] = scaler2.fit_transform(df[['long']])

In [ ]:
df['loc_of_card_holder'] = df.apply(lambda x: (x['lat'],x['long']),axis=1)

In [ ]:
#convert merch_loc and merch_long first
df.merch_lat = scaler.fit_transform(df[['merch_lat']])
df.merch_long = scaler.fit_transform(df[['merch_long']])

In [ ]:
#create merchant location
df['merch_loc'] = df.apply(lambda x: (x['merch_lat'],x['merch_long']),axis=1)

In [ ]:
df[df.is_fraud == 1].merch_loc.value_counts()

merch_loc
(-1.403989420307645, 0.02136039342823272)     1
(-0.41238789256895664, 0.6569548900241469)    1
(0.39036366677861, -1.4751831700546427)       1
(0.34478367931959203, -1.5168919380550907)    1
(-1.2857801738157602, -0.9579148598027879)    1
                                             ..
(-0.49938017859832073, 0.6421540957344308)    1
(-0.4989515892544915, 0.6515196611648382)     1
(-1.7125788361401528, -0.614108840708832)     1
(-0.5143162236764319, 0.5907635199799364)     1
(-1.8130411568482556, -0.6252154453933473)    1
Name: count, Length: 7506, dtype: int64

In [ ]:
df[df.is_fraud == 1].loc_of_card_holder.value_counts()

loc_of_card_holder
(0.43955150638704116, 0.717136710682252)        24
(0.7838711738818592, 0.5264261694137575)        23
(0.8800923363264845, -1.3569276407991862)       21
(0.4566522371409172, 0.7623432490469639)        21
(1.831547049492062, 0.012990366160267814)       19
                                                ..
(-1.212422427303414, -0.3371568040642857)        2
(-1.2051723479054572, 0.37406123850092465)       2
(-0.9802031722389619, -1.586557959068168)        2
(-0.8417424167801545, 0.8982681172940442)        2
(-1.5915936992954778, -0.049157722192890996)     2
Name: count, Length: 754, dtype: int64

In [ ]:
df[df.is_fraud == 1].Name.value_counts()

Name
Scott Martin        27
Jennifer Scott      26
Robert James        22
Linda Davis         20
Susan Garcia        20
                    ..
Katherine Tucker     2
Jessica Ward         2
Debra Stark          2
Rebecca Erickson     2
William Perry        2
Name: count, Length: 754, dtype: int64

In [ ]:
df[df.is_fraud == 1]['Year and Month'].value_counts()

Year and Month
2019-12    592
2020-05    527
2019-02    517
2019-01    506
2019-03    494
2019-10    454
2020-03    444
2019-09    418
2019-05    408
2019-11    388
2019-08    382
2019-04    376
2019-06    354
2020-01    343
2020-02    336
2020-06    334
2019-07    331
2020-04    302
Name: count, dtype: int64

In [ ]:
df[df.is_fraud == 1].Date.value_counts()

Date
2019-02-25    50
2019-02-12    44
2019-02-28    44
2019-05-20    44
2019-06-29    43
              ..
2020-02-26     1
2019-07-30     1
2019-08-06     1
2019-10-25     1
2020-04-04     1
Name: count, Length: 504, dtype: int64

In [ ]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [ ]:
df.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud', 'Date', 'Year and Month', 'Name',
       'loc_of_card_holder', 'merch_loc'],
      dtype='object')

In [ ]:
df.isna().sum()

trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
Date                     0
Year and Month           0
Name                     0
loc_of_card_holder       0
merch_loc                0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [trans_date_trans_time, cc_num, merchant, category, amt, first, last, gender, street, city, state, zip, lat, long, city_pop, job, dob, trans_num, unix_time, merch_lat, merch_long, is_fraud, Date, Year and Month, Name, loc_of_card_holder, merch_loc]
Index: []

[0 rows x 27 columns]

In [ ]:
#help(df.dropna())

In [ ]:
df.dtypes

trans_date_trans_time     object
cc_num                     int64
merchant                  object
category                  object
amt                      float64
first                     object
last                      object
gender                    object
street                    object
city                      object
state                     object
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                       object
dob                       object
trans_num                 object
unix_time                  int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
Date                      object
Year and Month            object
Name                      object
loc_of_card_holder        object
merch_loc                 object
dtype: object

In [ ]:
df.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud', 'Date', 'Year and Month', 'Name',
       'loc_of_card_holder', 'merch_loc'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x = df.drop(['is_fraud'],axis=1)
y = df.is_fraud

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,stratify=y,random_state=42)

In [ ]:
#create test and val set
x_val,x_test,y_val,y_test = train_test_split(x_test,y_test,test_size=0.5,stratify=y_test,random_state=42)

In [ ]:
y_train.sum()/len(y_train)

np.float64(0.005788434588706052)

In [ ]:
y_test.sum()/len(y_test)

np.float64(0.005789143556364459)

In [ ]:
len(x) == (len(x_train)+len(x_test)+len(x_val))

True

In [ ]:
#before normalizing lets split str and non str
strings = df[['trans_date_trans_time','merchant','category','first','last','gender','street','city','state','job','dob','trans_num','Date','Year and Month','Name','loc_of_card_holder','merch_loc']]
non_strings = df.drop(['trans_date_trans_time','merchant','category','first','last','gender','street','city','state','job','dob','trans_num','Date','Year and Month','Name','loc_of_card_holder','merch_loc','is_fraud'],axis=1)

In [ ]:
#before normalizing lets split str and non str
strings_train = x_train[['trans_date_trans_time','merchant','category','first','last','gender','street','city','state','job','dob','trans_num','Date','Year and Month','Name','loc_of_card_holder','merch_loc']]
non_strings_train = x_train.drop(['trans_date_trans_time','merchant','category','first','last','gender','street','city','state','job','dob','trans_num','Date','Year and Month','Name','loc_of_card_holder','merch_loc'],axis=1)

In [ ]:
#val set
strings_val = x_val[['trans_date_trans_time','merchant','category','first','last','gender','street','city','state','job','dob','trans_num','Date','Year and Month','Name','loc_of_card_holder','merch_loc']]
non_strings_val = x_val.drop(['trans_date_trans_time','merchant','category','first','last','gender','street','city','state','job','dob','trans_num','Date','Year and Month','Name','loc_of_card_holder','merch_loc'],axis=1)

In [ ]:
#test set
strings_test = x_test[['trans_date_trans_time','merchant','category','first','last','gender','street','city','state','job','dob','trans_num','Date','Year and Month','Name','loc_of_card_holder','merch_loc']]
non_strings_test = x_test.drop(['trans_date_trans_time','merchant','category','first','last','gender','street','city','state','job','dob','trans_num','Date','Year and Month','Name','loc_of_card_holder','merch_loc'],axis=1)

In [ ]:
scaler = StandardScaler()
non_strings_train = scaler.fit_transform(non_strings_train)
non_strings_val = scaler.transform(non_strings_val)
non_strings_test = scaler.transform(non_strings_test)

In [ ]:
strings_train

,trans_date_trans_time,merchant,category,first,last,gender,street,city,state,job,dob,trans_num,Date,Year and Month,Name,loc_of_card_holder,merch_loc
192318,2019-04-08 23:46:57,fraud_Stamm-Witting,shopping_net,Kimberly,Gonzalez,F,72966 Shannon Pass Apt. 391,Bauxite,AR,"Scientist, audiological",1975-12-20,9aaaca62069865fbf71b91dc69c75bfe,2019-04-08,2019-04,Kimberly Gonzalez,"(-0.7936712381632661, -0.16399831909012771)","(-0.6994263097111247, -0.15063251462544258)"
318906,2019-06-02 12:25:41,"fraud_Lowe, Dietrich and Erdman",kids_pets,Kayla,Obrien,F,7921 Robert Port Suite 343,Prairie Hill,TX,Barrister,1956-05-30,385daf000418e8ba543be01d6e0c3afd,2019-06-02,2019-06,Kayla Obrien,"(-1.3551583654506918, -0.478452674216755)","(-1.2853936605947265, -0.5082758600067984)"
212432,2019-04-18 17:44:59,fraud_Kub PLC,personal_care,Monique,Fox,F,755 Gardner Heights Apt. 420,Paxton,MA,Accounting technician,1926-09-14,382655367638cad7e4eaa69b08189cfa,2019-04-18,2019-04,Monique Fox,"(0.7425378407924211, 1.3304775101353123)","(0.7597558198919494, 1.3259758008414817)"
979043,2020-02-01 23:01:47,fraud_Streich Ltd,home,Allison,Ayala,F,87665 Karen Mill Apt. 586,Fort Myers,FL,Paramedic,1985-08-29,99c9a24d56636fa6d3c6b3b6ab5b4682,2020-02-01,2020-02,Allison Ayala,"(-2.377045235811095, 0.611533655627708)","(-2.239949021389021, 0.6309493143285473)"
614236,2019-09-17 23:20:40,fraud_Waters-Cruickshank,health_fitness,Kimberly,Miller,F,75533 Tamara Valleys,Logan,IL,"Scientist, research (physical sciences)",1976-06-15,fb1cb28957e0faa76191cc31dbe2a21d,2019-09-17,2019-09,Kimberly Miller,"(-0.10704143605023428, 0.09336642850357178)","(-0.1612979448234471, 0.06142804167797675)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125527,2019-03-10 21:06:15,"fraud_Effertz, Welch and Schowalter",entertainment,Allison,Ayala,F,87665 Karen Mill Apt. 586,Fort Myers,FL,Paramedic,1985-08-29,c48d6c3a05a7664205f4845193b6c8f9,2019-03-10,2019-03,Allison Ayala,"(-2.377045235811095, 0.611533655627708)","(-2.2606097676021544, 0.5474036112320781)"
150047,2019-03-22 05:06:39,fraud_Pacocha-Bauch,shopping_pos,Christian,Roman,M,495 Fisher Throughway,Grand Junction,TN,Clothing/textile technologist,1974-10-15,bc7c080346a8d8856ce0e4996462ed46,2019-03-22,2019-03,Christian Roman,"(-0.6839743846637433, 0.07798021600870066)","(-0.6887158815791173, 0.13292676394959374)"
1151888,2020-04-25 18:11:52,fraud_Abernathy and Sons,food_dining,Jamie,Carr,F,55363 Aaron Circle Suite 450,Lawn,PA,Special educational needs teacher,1972-02-15,2a12827950e508d617add087df49687a,2020-04-25,2020-04,Jamie Carr,"(0.332159705304803, 0.9948589364044982)","(0.323633871567541, 0.9349696527830229)"
547306,2019-08-22 14:59:38,fraud_Windler LLC,kids_pets,Jared,Velazquez,M,01479 Murray Circle,Matawan,NJ,Drilling engineer,1993-04-29,427c30a2bad445bbbdb0377ce7ccfbcf,2019-08-22,2019-08,Jared Velazquez,"(0.3690602452840785, 1.1620213773029502)","(0.3021175122899233, 1.2193751972684443)"
33493,2019-01-20 22:31:23,fraud_Erdman-Ebert,personal_care,Jenna,Brooks,F,50872 Alex Plain Suite 088,Baton Rouge,LA,"Designer, furniture",1977-02-22,a9d6576c8c5869e570e0ca7d1aac7c50,2019-01-20,2019-01,Jenna Brooks,"(-1.6019171819164812, -0.06689874472476608)","(-1.6504390566688893, -0.12646056347962176)"

In [ ]:
non_strings_train_df = pd.DataFrame(non_strings_train, columns=non_strings.columns)
x_train_processed = pd.concat([strings_train.reset_index(drop=True), non_strings_train_df.reset_index(drop=True)], axis=1)

In [ ]:
len(x_train) == len(x_train_processed)

True

In [ ]:
non_strings_val_df = pd.DataFrame(non_strings_val,columns=non_strings.columns)
x_val_processed = pd.concat([strings_val.reset_index(drop=True), non_strings_val_df.reset_index(drop=True)], axis=1)

In [ ]:
non_strings_test_df = pd.DataFrame(non_strings_test,columns=non_strings.columns)
x_test_processed = pd.concat([strings_test.reset_index(drop=True),non_strings_test_df.reset_index(drop=True)],axis=1)

In [ ]:
len(x_test) == len(x_test_processed)

True

In [ ]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (8.5.0)
Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 9.0 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8

In [ ]:
from catboost import CatBoostClassifier

In [ ]:
#cat boost can't handle tuples so drop merch_loc and loc_of_card_holder
x_train_processed.drop(['merch_loc','loc_of_card_holder'],axis=1,inplace=True)
x_train_processed.columns

Index(['trans_date_trans_time', 'merchant', 'category', 'first', 'last',
       'gender', 'street', 'city', 'state', 'job', 'dob', 'trans_num', 'Date',
       'Year and Month', 'Name', 'cc_num', 'amt', 'zip', 'lat', 'long',
       'city_pop', 'unix_time', 'merch_lat', 'merch_long'],
      dtype='object')

In [ ]:
x_test_processed.drop(['merch_loc','loc_of_card_holder'],axis=1,inplace=True)
x_val_processed.drop(['merch_loc','loc_of_card_holder'],axis=1,inplace=True)

In [ ]:
model = CatBoostClassifier(verbose=True,
                           cat_features=list(['merchant', 'category', 'street', 'city', 'job', 'dob', 'Date', 'Name']),
                           learning_rate=0.03,
                           depth=8,
                           eval_metric='F1',
                           l2_leaf_reg=5.0,
                           random_strength = 2.0,
                           bagging_temperature=5.0,
                           auto_class_weights='Balanced',
                           od_type='Iter',
                           od_wait=50,
                           use_best_model=True)

In [ ]:
#help(CatBoostClassifier)

In [ ]:
model.fit(x_train_processed,y_train,eval_set=(x_val_processed,y_val))

0:	learn: 0.9046951	test: 0.9028333	best: 0.9028333 (0)	total: 3.75s	remaining: 1h 2m 29s
1:	learn: 0.9014535	test: 0.8986286	best: 0.9028333 (0)	total: 5.05s	remaining: 42m 2s
2:	learn: 0.9064336	test: 0.9029320	best: 0.9029320 (2)	total: 9.05s	remaining: 50m 9s
3:	learn: 0.9017101	test: 0.8996422	best: 0.9029320 (2)	total: 13s	remaining: 53m 53s
4:	learn: 0.9026252	test: 0.9003495	best: 0.9029320 (2)	total: 16.3s	remaining: 54m 9s
5:	learn: 0.9035215	test: 0.9012557	best: 0.9029320 (2)	total: 20.9s	remaining: 57m 35s
6:	learn: 0.9025949	test: 0.9014342	best: 0.9029320 (2)	total: 23.4s	remaining: 55m 24s
7:	learn: 0.9022800	test: 0.9016773	best: 0.9029320 (2)	total: 24.7s	remaining: 50m 57s
8:	learn: 0.9025467	test: 0.9009224	best: 0.9029320 (2)	total: 25.5s	remaining: 46m 46s
9:	learn: 0.9029996	test: 0.9006225	best: 0.9029320 (2)	total: 28.3s	remaining: 46m 37s
10:	learn: 0.9022166	test: 0.8999169	best: 0.9029320 (2)	total: 31.1s	remaining: 46m 32s
11:	learn: 0.9028717	test: 0.9005903	best: 0.9029320 (2)	total: 32.8s	remaining: 45m 1s
12:	learn: 0.9019811	test: 0.9010240	best: 0.9029320 (2)	total: 36.8s	remaining: 46m 31s
13:	learn: 0.9135538	test: 0.9152886	best: 0.9152886 (13)	total: 39s	remaining: 45m 48s
14:	learn: 0.9461046	test: 0.9598522	best: 0.9598522 (14)	total: 41.8s	remaining: 45m 46s
15:	learn: 0.9458091	test: 0.9597122	best: 0.9598522 (14)	total: 44.5s	remaining: 45m 37s
16:	learn: 0.9477059	test: 0.9631761	best: 0.9631761 (16)	total: 47.3s	remaining: 45m 37s
17:	learn: 0.9628821	test: 0.9842005	best: 0.9842005 (17)	total: 52.1s	remaining: 47m 24s
18:	learn: 0.9642397	test: 0.9860962	best: 0.9860962 (18)	total: 55.4s	remaining: 47m 40s
19:	learn: 0.9643512	test: 0.9857996	best: 0.9860962 (18)	total: 56.1s	remaining: 45m 47s
20:	learn: 0.9644226	test: 0.9861340	best: 0.9861340 (20)	total: 59.6s	remaining: 46m 19s
21:	learn: 0.9647815	test: 0.9862651	best: 0.9862651 (21)	total: 1m 4s	remaining: 47m 36s
22:	learn: 0.9659809	test: 0.9884536	best: 0.9884536 (22)	total: 1m 7s	remaining: 48m 6s
23:	learn: 0.9669848	test: 0.9892597	best: 0.9892597 (23)	total: 1m 11s	remaining: 48m 8s
24:	learn: 0.9672572	test: 0.9898790	best: 0.9898790 (24)	total: 1m 13s	remaining: 47m 35s
25:	learn: 0.9677891	test: 0.9898714	best: 0.9898790 (24)	total: 1m 17s	remaining: 48m 27s
26:	learn: 0.9717487	test: 0.9952522	best: 0.9952522 (26)	total: 1m 21s	remaining: 48m 57s
27:	learn: 0.9718229	test: 0.9952060	best: 0.9952522 (26)	total: 1m 24s	remaining: 49m
28:	learn: 0.9717769	test: 0.9951316	best: 0.9952522 (26)	total: 1m 28s	remaining: 49m 11s
29:	learn: 0.9722807	test: 0.9959151	best: 0.9959151 (29)	total: 1m 33s	remaining: 50m 21s
30:	learn: 0.9723368	test: 0.9958817	best: 0.9959151 (29)	total: 1m 37s	remaining: 50m 34s
31:	learn: 0.9721680	test: 0.9958175	best: 0.9959151 (29)	total: 1m 37s	remaining: 49m 22s
32:	learn: 0.9721444	test: 0.9957686	best: 0.9959151 (29)	total: 1m 38s	remaining: 48m 13s
33:	learn: 0.9720520	test: 0.9956684	best: 0.9959151 (29)	total: 1m 39s	remaining: 47m 8s
34:	learn: 0.9723975	test: 0.9962881	best: 0.9962881 (34)	total: 1m 42s	remaining: 47m 14s
35:	learn: 0.9726237	test: 0.9965558	best: 0.9965558 (35)	total: 1m 48s	remaining: 48m 14s
36:	learn: 0.9725935	test: 0.9965043	best: 0.9965558 (35)	total: 1m 51s	remaining: 48m 14s
37:	learn: 0.9726768	test: 0.9966356	best: 0.9966356 (37)	total: 1m 54s	remaining: 48m 13s
38:	learn: 0.9727343	test: 0.9967180	best: 0.9967180 (38)	total: 1m 57s	remaining: 48m 15s
39:	learn: 0.9728121	test: 0.9967721	best: 0.9967721 (39)	total: 2m 2s	remaining: 49m 9s
40:	learn: 0.9728258	test: 0.9968467	best: 0.9968467 (40)	total: 2m 6s	remaining: 49m 13s
41:	learn: 0.9728433	test: 0.9968571	best: 0.9968571 (41)	total: 2m 9s	remaining: 49m 23s
42:	learn: 0.9728576	test: 0.9968699	best: 0.9968699 (42)	total: 2m 15s	remaining: 50m 8s
43:	learn: 0.9727511	test: 0.9968699	best: 0.9968699 (42)	total: 2m 16s	remaining: 49m 19s
44:	learn: 0.9728543	test: 0.9968622	best: 0.9968699 (42)	total: 2m 17s	remaining: 48m 42s
45:	learn: 0.9727434	test: 0.9968596	best: 0.9968699 (42)	total: 2m 18s	remaining: 47m 51s
46:	learn: 0.9727604	test: 0.9968699	best: 0.9968699 (42)	total: 2m 21s	remaining: 47m 57s
47:	learn: 0.9727763	test: 0.9968777	best: 0.9968777 (47)	total: 2m 24s	remaining: 47m 45s
48:	learn: 0.9728037	test: 0.9968931	best: 0.9968931 (48)	total: 2m 29s	remaining: 48m 15s
49:	learn: 0.9729222	test: 0.9968983	best: 0.9968983 (49)	total: 2m 32s	remaining: 48m 21s
50:	learn: 0.9729277	test: 0.9969034	best: 0.9969034 (50)	total: 2m 34s	remaining: 47m 57s
51:	learn: 0.9729370	test: 0.9969060	best: 0.9969060 (51)	total: 2m 38s	remaining: 48m 2s
52:	learn: 0.9730534	test: 0.9969060	best: 0.9969060 (51)	total: 2m 42s	remaining: 48m 22s
53:	learn: 0.9730572	test: 0.9969060	best: 0.9969060 (51)	total: 2m 45s	remaining: 48m 11s
54:	learn: 0.9730687	test: 0.9969112	best: 0.9969112 (54)	total: 2m 48s	remaining: 48m 22s
55:	learn: 0.9730693	test: 0.9969112	best: 0.9969112 (54)	total: 2m 49s	remaining: 47m 41s
56:	learn: 0.9730912	test: 0.9969215	best: 0.9969215 (56)	total: 2m 53s	remaining: 47m 47s
57:	learn: 0.9732021	test: 0.9969240	best: 0.9969240 (57)	total: 2m 58s	remaining: 48m 25s
58:	learn: 0.9732021	test: 0.9969240	best: 0.9969240 (57)	total: 2m 59s	remaining: 47m 46s
59:	learn: 0.9732295	test: 0.9969395	best: 0.9969395 (59)	total: 3m 3s	remaining: 47m 51s
60:	learn: 0.9732295	test: 0.9969343	best: 0.9969395 (59)	total: 3m 6s	remaining: 47m 48s
61:	learn: 0.9733337	test: 0.9969498	best: 0.9969498 (61)	total: 3m 10s	remaining: 47m 55s
62:	learn: 0.9733655	test: 0.9969575	best: 0.9969575 (62)	total: 3m 14s	remaining: 48m 10s
63:	learn: 0.9733727	test: 0.9969807	best: 0.9969807 (63)	total: 3m 17s	remaining: 48m 13s
64:	learn: 0.9733737	test: 0.9969807	best: 0.9969807 (63)	total: 3m 18s	remaining: 47m 31s
65:	learn: 0.9733885	test: 0.9969859	best: 0.9969859 (65)	total: 3m 22s	remaining: 47m 40s
66:	learn: 0.9735038	test: 0.9969910	best: 0.9969910 (66)	total: 3m 27s	remaining: 48m 7s
67:	learn: 0.9735092	test: 0.9970065	best: 0.9970065 (67)	total: 3m 29s	remaining: 47m 54s
68:	learn: 0.9737116	test: 0.9970142	best: 0.9970142 (68)	total: 3m 33s	remaining: 47m 58s
69:	learn: 0.9737089	test: 0.9970142	best: 0.9970142 (68)	total: 3m 38s	remaining: 48m 17s
70:	learn: 0.9736996	test: 0.9970142	best: 0.9970142 (68)	total: 3m 42s	remaining: 48m 32s
71:	learn: 0.9737018	test: 0.9970194	best: 0.9970194 (71)	total: 3m 44s	remaining: 48m 15s
72:	learn: 0.9739095	test: 0.9970245	best: 0.9970245 (72)	total: 3m 48s	remaining: 48m 17s
73:	learn: 0.9739117	test: 0.9970271	best: 0.9970271 (73)	total: 3m 50s	remaining: 48m
74:	learn: 0.9739128	test: 0.9970322	best: 0.9970322 (74)	total: 3m 54s	remaining: 48m 18s
75:	learn: 0.9740153	test: 0.9970374	best: 0.9970374 (75)	total: 3m 58s	remaining: 48m 23s
76:	learn: 0.9740181	test: 0.9970348	best: 0.9970374 (75)	total: 4m 1s	remaining: 48m 18s
77:	learn: 0.9740208	test: 0.9970374	best: 0.9970374 (75)	total: 4m 5s	remaining: 48m 16s
78:	learn: 0.9741227	test: 0.9970400	best: 0.9970400 (78)	total: 4m 9s	remaining: 48m 28s
79:	learn: 0.9741244	test: 0.9970426	best: 0.9970426 (79)	total: 4m 10s	remaining: 47m 58s
80:	learn: 0.9742395	test: 0.9970554	best: 0.9970554 (80)	total: 4m 14s	remaining: 48m 1s
81:	learn: 0.9742384	test: 0.9970529	best: 0.9970554 (80)	total: 4m 14s	remaining: 47m 32s
82:	learn: 0.9744421	test: 0.9970580	best: 0.9970580 (82)	total: 4m 18s	remaining: 47m 34s
83:	learn: 0.9745506	test: 0.9970786	best: 0.9970786 (83)	total: 4m 24s	remaining: 48m
84:	learn: 0.9744460	test: 0.9970709	best: 0.9970786 (83)	total: 4m 27s	remaining: 48m 1s
85:	learn: 0.9744515	test: 0.9970838	best: 0.9970838 (85)	total: 4m 30s	remaining: 48m
86:	learn: 0.9745451	test: 0.9970812	best: 0.9970838 (85)	total: 4m 34s	remaining: 48m 3s
87:	learn: 0.9745467	test: 0.9970812	best: 0.9970838 (85)	total: 4m 36s	remaining: 47m 46s
88:	learn: 0.9745517	test: 0.9970864	best: 0.9970864 (88)	total: 4m 40s	remaining: 47m 53s
89:	learn: 0.9745593	test: 0.9970941	best: 0.9970941 (89)	total: 4m 43s	remaining: 47m 47s
90:	learn: 0.9745577	test: 0.9970941	best: 0.9970941 (89)	total: 4m 44s	remaining: 47m 21s
91:	learn: 0.9747652	test: 0.9971096	best: 0.9971096 (91)	total: 4m 48s	remaining: 47m 23s
92:	learn: 0.9747685	test: 0.9971121	best: 0.9971121 (92)	total: 4m 53s	remaining: 47m 37s
93:	learn: 0.9748582	test: 0.9971070	best: 0.9971121 (92)	total: 4m 55s	remaining: 47m 29s
94:	learn: 0.9748555	test: 0.9971044	best: 0.9971121 (92)	total: 4m 59s	remaining: 47m 29s
95:	learn: 0.9748538	test: 0.9971044	best: 0.9971121 (92)	total: 5m	remaining: 47m 5s
96:	learn: 0.9749622	test: 0.9971224	best: 0.9971224 (96)	total: 5m 4s	remaining: 47m 16s
97:	learn: 0.9750760	test: 0.9971379	best: 0.9971379 (97)	total: 5m 8s	remaining: 47m 18s
98:	learn: 0.9750815	test: 0.9971379	best: 0.9971379 (97)	total: 5m 9s	remaining: 46m 57s
99:	learn: 0.9750870	test: 0.9971456	best: 0.9971456 (99)	total: 5m 12s	remaining: 46m 53s
100:	learn: 0.9752959	test: 0.9971688	best: 0.9971688 (100)	total: 5m 16s	remaining: 46m 57s
101:	learn: 0.9752987	test: 0.9971714	best: 0.9971714 (101)	total: 5m 20s	remaining: 47m
102:	learn: 0.9752959	test: 0.9971688	best: 0.9971714 (101)	total: 5m 21s	remaining: 46m 37s
103:	learn: 0.9752959	test: 0.9971714	best: 0.9971714 (101)	total: 5m 24s	remaining: 46m 34s
104:	learn: 0.9755070	test: 0.9971792	best: 0.9971792 (104)	total: 5m 27s	remaining: 46m 35s
105:	learn: 0.9755092	test: 0.9971972	best: 0.9971972 (105)	total: 5m 33s	remaining: 46m 49s
106:	learn: 0.9755158	test: 0.9971998	best: 0.9971998 (106)	total: 5m 36s	remaining: 46m 51s
107:	learn: 0.9756169	test: 0.9972101	best: 0.9972101 (107)	total: 5m 40s	remaining: 46m 55s
108:	learn: 0.9759113	test: 0.9972127	best: 0.9972127 (108)	total: 5m 45s	remaining: 47m 4s
109:	learn: 0.9760069	test: 0.9972049	best: 0.9972127 (108)	total: 5m 50s	remaining: 47m 12s
110:	learn: 0.9760986	test: 0.9972049	best: 0.9972127 (108)	total: 5m 53s	remaining: 47m 10s
111:	learn: 0.9759937	test: 0.9972075	best: 0.9972127 (108)	total: 5m 56s	remaining: 47m 3s
112:	learn: 0.9760931	test: 0.9972152	best: 0.9972152 (112)	total: 5m 59s	remaining: 47m
113:	learn: 0.9760931	test: 0.9972152	best: 0.9972152 (112)	total: 6m 2s	remaining: 46m 56s
114:	learn: 0.9761924	test: 0.9972152	best: 0.9972152 (112)	total: 6m 5s	remaining: 46m 56s
115:	learn: 0.9761935	test: 0.9972178	best: 0.9972178 (115)	total: 6m 9s	remaining: 46m 57s
116:	learn: 0.9761963	test: 0.9972204	best: 0.9972204 (116)	total: 6m 13s	remaining: 46m 56s
117:	learn: 0.9761870	test: 0.9972127	best: 0.9972204 (116)	total: 6m 18s	remaining: 47m 6s
118:	learn: 0.9761930	test: 0.9972230	best: 0.9972230 (118)	total: 6m 21s	remaining: 47m 2s
119:	learn: 0.9761930	test: 0.9972230	best: 0.9972230 (118)	total: 6m 21s	remaining: 46m 39s
120:	learn: 0.9761919	test: 0.9972230	best: 0.9972230 (118)	total: 6m 22s	remaining: 46m 21s
121:	learn: 0.9761903	test: 0.9972230	best: 0.9972230 (118)	total: 6m 25s	remaining: 46m 13s
122:	learn: 0.9763049	test: 0.9972359	best: 0.9972359 (122)	total: 6m 29s	remaining: 46m 19s
123:	learn: 0.9762094	test: 0.9972384	best: 0.9972384 (123)	total: 6m 34s	remaining: 46m 23s
124:	learn: 0.9762149	test: 0.9972539	best: 0.9972539 (124)	total: 6m 37s	remaining: 46m 23s
125:	learn: 0.9763176	test: 0.9972565	best: 0.9972565 (125)	total: 6m 41s	remaining: 46m 24s
126:	learn: 0.9763060	test: 0.9972488	best: 0.9972565 (125)	total: 6m 46s	remaining: 46m 32s
127:	learn: 0.9764119	test: 0.9972513	best: 0.9972565 (125)	total: 6m 49s	remaining: 46m 29s
128:	learn: 0.9764191	test: 0.9972513	best: 0.9972565 (125)	total: 6m 53s	remaining: 46m 30s
129:	learn: 0.9764125	test: 0.9972513	best: 0.9972565 (125)	total: 6m 58s	remaining: 46m 37s
130:	learn: 0.9765101	test: 0.9972513	best: 0.9972565 (125)	total: 7m 1s	remaining: 46m 37s
131:	learn: 0.9766083	test: 0.9972616	best: 0.9972616 (131)	total: 7m 5s	remaining: 46m 37s
132:	learn: 0.9766083	test: 0.9972591	best: 0.9972616 (131)	total: 7m 6s	remaining: 46m 17s
133:	learn: 0.9766187	test: 0.9972616	best: 0.9972616 (131)	total: 7m 8s	remaining: 46m 11s
134:	learn: 0.9766226	test: 0.9972642	best: 0.9972642 (134)	total: 7m 13s	remaining: 46m 15s
135:	learn: 0.9767207	test: 0.9972720	best: 0.9972720 (135)	total: 7m 17s	remaining: 46m 17s
136:	learn: 0.9767207	test: 0.9972720	best: 0.9972720 (135)	total: 7m 17s	remaining: 45m 58s
137:	learn: 0.9770058	test: 0.9972694	best: 0.9972720 (135)	total: 7m 19s	remaining: 45m 45s
138:	learn: 0.9771653	test: 0.9972977	best: 0.9972977 (138)	total: 7m 21s	remaining: 45m 37s
139:	learn: 0.9771653	test: 0.9972977	best: 0.9972977 (138)	total: 7m 22s	remaining: 45m 17s
140:	learn: 0.9772634	test: 0.9972977	best: 0.9972977 (138)	total: 7m 26s	remaining: 45m 18s
141:	learn: 0.9772617	test: 0.9972977	best: 0.9972977 (138)	total: 7m 26s	remaining: 45m
142:	learn: 0.9772612	test: 0.9972977	best: 0.9972977 (138)	total: 7m 30s	remaining: 44m 57s
143:	learn: 0.9772579	test: 0.9972952	best: 0.9972977 (138)	total: 7m 31s	remaining: 44m 44s
144:	learn: 0.9772579	test: 0.9972952	best: 0.9972977 (138)	total: 7m 32s	remaining: 44m 28s

In [ ]:
model.feature_importances_

array([ 3.71255432, 12.39446938,  7.82218353,  9.07660968,  2.53235566,
        8.74652723, 20.61122797,  5.95696239, 29.14710984])

In [ ]:
sorted_importance = sorted(zip(x_test_processed.columns, model.feature_importances_), key=lambda x: x[1], reverse=True)
for name, score in sorted_importance:
    print(f"{name}: {score:.4f}")

amt: 29.1471
Date: 20.6112
category: 12.3945
city: 9.0766
dob: 8.7465
street: 7.8222
Name: 5.9570
merchant: 3.7126
job: 2.5324

In [ ]:
#Remove columns
"""x_train_processed.drop(['Year and Month','last','state','first','city_pop','zip','gender','long','lat','unix_time','cc_num','merch_lat','merch_long','trans_date_trans_time','trans_num'],axis=1,inplace=True)
x_test_processed.drop(['Year and Month','last','state','first','city_pop','zip','gender','long','lat','unix_time','cc_num','merch_lat','merch_long','trans_date_trans_time','trans_num'],axis=1,inplace=True)
x_val_processed.drop(['Year and Month','last','state','first','city_pop','zip','gender','long','lat','unix_time','cc_num','merch_lat','merch_long','trans_date_trans_time','trans_num'],axis=1,inplace=True)
"""

In [ ]:
x_train_processed.columns == x_test_processed.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
x_train_processed.columns == x_val_processed.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
x_val_processed

,merchant,category,street,city,job,dob,Date,Name,amt
0,fraud_Abernathy and Sons,food_dining,1980 Vasquez Manors Apt. 574,Catawba,Equality and diversity officer,1940-08-23,2019-12-12,Misty Rivera,-0.256953
1,fraud_Abernathy and Sons,food_dining,840 Werner Lock Apt. 852,Campbell,"Surveyor, minerals",1940-09-13,2019-04-27,Amber Thornton,0.104702
2,"fraud_Hoppe, Harris and Bednar",entertainment,9554 Flores Drive,Arnold,Land/geomatics surveyor,1985-03-31,2019-08-18,Francisco Kemp,-0.400169
3,fraud_Koepp-Witting,grocery_pos,4720 Anna Ways,Murrayville,Commercial/residential surveyor,2003-05-07,2019-11-30,Jason Singh,0.019353
4,fraud_Schimmel-Olson,kids_pets,5916 Susan Bridge Apt. 939,Grenada,Systems analyst,1945-12-21,2020-05-12,Jack Hill,-0.060062
...,...,...,...,...,...,...,...,...,...
194496,"fraud_Klocko, Runolfsdottir and Breitenberg",health_fitness,5395 Colon Burgs Suite 037,Thrall,Press sub,1976-01-02,2019-06-03,Danielle Yu,-0.012581
194497,fraud_Johnston-Casper,travel,8614 Reed Glen,West Harrison,Lexicographer,1977-08-16,2019-10-29,Kenneth Doyle,-0.444038
194498,fraud_Nolan-Williamson,kids_pets,75533 Tamara Valleys,Logan,"Scientist, research (physical sciences)",1976-06-15,2020-04-29,Kimberly Miller,0.031030
194499,"fraud_Zieme, Bode and Dooley",gas_transport,1742 Brandon Squares Apt. 461,Ruidoso,Licensed conveyancer,2000-08-16,2019-07-31,Michelle Rodriguez,-0.198247
194500,"fraud_Schiller, Blanda and Johnson",home,6139 Mark Rapid Apt. 651,Christine,Television floor manager,1991-05-01,2019-03-31,Micheal Hernandez,-0.008194

###Retrain model

In [ ]:
from sklearn.metrics import f1_score,accuracy_score

In [ ]:
f1_score(y_test,model.predict(x_test_processed))

0.9153374233128835

In [ ]:
pd.read_csv('/content/sample_data/california_housing_test.csv')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0