<a href="https://colab.research.google.com/github/Srihari0804/Desicion-Trees/blob/main/Glass_identification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('/content/glass.csv')

In [ ]:
df

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [ ]:
df.Type.value_counts()

Type
2    76
1    70
7    29
3    17
5    13
6     9
Name: count, dtype: int64

In [ ]:
df.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [ ]:
df.duplicated().any()

np.True_

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(213, 10)

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('Type',axis=1),df['Type'], stratify=df['Type'],random_state=42,test_size=0.3)

In [ ]:
x_val,x_test,y_val,y_test = train_test_split(x_test,y_test,stratify=y_test,random_state=42)

In [ ]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
x_val = scaler.transform(x_val)

In [ ]:
#!pip install catboost

In [ ]:
from catboost import CatBoostClassifier

In [ ]:
model = CatBoostClassifier(
    n_estimators=50,
    l2_leaf_reg=5,
    learning_rate= 0.1,
    loss_function='MultiClass',
    eval_metric='Accuracy',

    od_type="Iter",
    od_wait=50,
    random_state=42,

)

In [ ]:
model.fit(x_train,y_train,eval_set=(x_val,y_val))

0:	learn: 0.6979866	test: 0.5208333	best: 0.5208333 (0)	total: 5.76ms	remaining: 282ms
1:	learn: 0.7382550	test: 0.6458333	best: 0.6458333 (1)	total: 9.64ms	remaining: 231ms
2:	learn: 0.7382550	test: 0.6250000	best: 0.6458333 (1)	total: 13ms	remaining: 204ms
3:	learn: 0.7651007	test: 0.7500000	best: 0.7500000 (3)	total: 16.6ms	remaining: 191ms
4:	learn: 0.7651007	test: 0.7291667	best: 0.7500000 (3)	total: 20.2ms	remaining: 182ms
5:	learn: 0.7986577	test: 0.7083333	best: 0.7500000 (3)	total: 23.6ms	remaining: 173ms
6:	learn: 0.7919463	test: 0.7291667	best: 0.7500000 (3)	total: 27.3ms	remaining: 168ms
7:	learn: 0.8187919	test: 0.7708333	best: 0.7708333 (7)	total: 30.9ms	remaining: 162ms
8:	learn: 0.8187919	test: 0.7916667	best: 0.7916667 (8)	total: 34.3ms	remaining: 156ms
9:	learn: 0.8187919	test: 0.7708333	best: 0.7916667 (8)	total: 37.8ms	remaining: 151ms
10:	learn: 0.8120805	test: 0.7916667	best: 0.7916667 (8)	total: 41.1ms	remaining: 146ms
11:	learn: 0.8187919	test: 0.7916667	best: 0.7916667 (8)	total: 44.7ms	remaining: 141ms
12:	learn: 0.8322148	test: 0.7916667	best: 0.7916667 (8)	total: 48ms	remaining: 137ms
13:	learn: 0.8322148	test: 0.7916667	best: 0.7916667 (8)	total: 51.4ms	remaining: 132ms
14:	learn: 0.8322148	test: 0.7916667	best: 0.7916667 (8)	total: 54.9ms	remaining: 128ms
15:	learn: 0.8322148	test: 0.7916667	best: 0.7916667 (8)	total: 58.4ms	remaining: 124ms
16:	learn: 0.8322148	test: 0.7916667	best: 0.7916667 (8)	total: 61.7ms	remaining: 120ms
17:	learn: 0.8255034	test: 0.7916667	best: 0.7916667 (8)	total: 65.2ms	remaining: 116ms
18:	learn: 0.8255034	test: 0.7916667	best: 0.7916667 (8)	total: 68.5ms	remaining: 112ms
19:	learn: 0.8389262	test: 0.7708333	best: 0.7916667 (8)	total: 72ms	remaining: 108ms
20:	learn: 0.8389262	test: 0.7916667	best: 0.7916667 (8)	total: 75.6ms	remaining: 104ms
21:	learn: 0.8322148	test: 0.7916667	best: 0.7916667 (8)	total: 79ms	remaining: 101ms
22:	learn: 0.8389262	test: 0.7500000	best: 0.7916667 (8)	total: 82.4ms	remaining: 96.7ms
23:	learn: 0.8456376	test: 0.7500000	best: 0.7916667 (8)	total: 86ms	remaining: 93.1ms
24:	learn: 0.8456376	test: 0.7500000	best: 0.7916667 (8)	total: 89.6ms	remaining: 89.6ms
25:	learn: 0.8523490	test: 0.7916667	best: 0.7916667 (8)	total: 93.2ms	remaining: 86ms
26:	learn: 0.8523490	test: 0.7916667	best: 0.7916667 (8)	total: 96.8ms	remaining: 82.5ms
27:	learn: 0.8523490	test: 0.7500000	best: 0.7916667 (8)	total: 100ms	remaining: 78.9ms
28:	learn: 0.8523490	test: 0.7500000	best: 0.7916667 (8)	total: 104ms	remaining: 75.3ms
29:	learn: 0.8456376	test: 0.7500000	best: 0.7916667 (8)	total: 107ms	remaining: 71.6ms
30:	learn: 0.8456376	test: 0.7500000	best: 0.7916667 (8)	total: 111ms	remaining: 67.9ms
31:	learn: 0.8456376	test: 0.7500000	best: 0.7916667 (8)	total: 114ms	remaining: 64.3ms
32:	learn: 0.8523490	test: 0.7500000	best: 0.7916667 (8)	total: 118ms	remaining: 60.7ms
33:	learn: 0.8456376	test: 0.7500000	best: 0.7916667 (8)	total: 121ms	remaining: 57ms
34:	learn: 0.8523490	test: 0.7500000	best: 0.7916667 (8)	total: 125ms	remaining: 53.4ms
35:	learn: 0.8523490	test: 0.7500000	best: 0.7916667 (8)	total: 128ms	remaining: 49.8ms
36:	learn: 0.8590604	test: 0.7500000	best: 0.7916667 (8)	total: 132ms	remaining: 46.3ms
37:	learn: 0.8590604	test: 0.7500000	best: 0.7916667 (8)	total: 135ms	remaining: 42.7ms
38:	learn: 0.8590604	test: 0.7500000	best: 0.7916667 (8)	total: 139ms	remaining: 39.2ms
39:	learn: 0.8590604	test: 0.7500000	best: 0.7916667 (8)	total: 142ms	remaining: 35.6ms
40:	learn: 0.8523490	test: 0.7500000	best: 0.7916667 (8)	total: 146ms	remaining: 32ms
41:	learn: 0.8523490	test: 0.7500000	best: 0.7916667 (8)	total: 151ms	remaining: 28.7ms
42:	learn: 0.8590604	test: 0.7500000	best: 0.7916667 (8)	total: 154ms	remaining: 25.1ms
43:	learn: 0.8657718	test: 0.7500000	best: 0.7916667 (8)	total: 158ms	remaining: 21.6ms
44:	learn: 0.8657718	test: 0.7500000	best: 0.7916667 (8)	total: 162ms	remaining: 17.9ms
45:	learn: 0.8724832	test: 0.7500000	best: 0.7916667 (8)	total: 165ms	remaining: 14.3ms
46:	learn: 0.8657718	test: 0.7708333	best: 0.7916667 (8)	total: 169ms	remaining: 10.8ms
47:	learn: 0.8724832	test: 0.7500000	best: 0.7916667 (8)	total: 172ms	remaining: 7.17ms
48:	learn: 0.8724832	test: 0.7500000	best: 0.7916667 (8)	total: 176ms	remaining: 3.58ms
49:	learn: 0.8724832	test: 0.7500000	best: 0.7916667 (8)	total: 179ms	remaining: 0us

bestTest = 0.7916666667
bestIteration = 8

Shrink model to first 9 iterations.

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test,model.predict(x_test))

0.8012422360248448

In [ ]:
r2_score(y_train,model.predict(x_train))

0.8115386184666856

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model = RandomForestRegressor(
    max_depth=6,
    max_features=0.6,
    random_state=42,
    oob_score=True,
    verbose=1,
    max_samples=0.6
)

In [ ]:
model.fit(x_train,y_train)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.1s finished

RandomForestRegressor(max_depth=6, max_features=0.6, max_samples=0.6,
                      oob_score=True, random_state=42, verbose=1)

In [ ]:
r2_score(y_test,model.predict(x_test))

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished

0.8027237530288043

In [ ]:
r2_score(y_train,model.predict(x_train))

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished

0.9192527956622226

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
model = GradientBoostingClassifier(
    n_estimators= 100,
    verbose=1,
    learning_rate=0.2,
    random_state=42,
    max_depth=8
)

In [ ]:
model.fit(x_train,y_train)

      Iter       Train Loss   Remaining Time
         1           0.7113            1.87s
         2           0.4707            2.08s
         3           0.3233            2.20s
         4           0.2261            2.25s
         5           0.1591            2.24s
         6           0.1128            2.28s
         7           0.0803            2.33s
         8           0.0573            2.30s
         9           0.0410            2.30s
        10           0.0294            2.26s
        20           0.0010            1.98s
        30           0.0000            1.69s
        40           0.0000            1.39s
        50           0.0000            1.08s
        60           0.0000            0.76s
        70           0.0000            0.51s
        80           0.0000            0.30s
        90           0.0000            0.14s
       100           0.0000            0.00s

GradientBoostingClassifier(learning_rate=0.2, max_depth=8, random_state=42,
                           verbose=1)

In [ ]:
r2_score(y_test,model.predict(x_test))

0.485328330206379